
name: Unity CI

on: [push, pull_request]

jobs:
  unity_test:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    environment: UnityProject
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Test Runner
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  windows_build:
    needs: unity_test
    name: Unity Build (Windows)
    runs-on: ubuntu-latest
    environment: UnityProject
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true

  android_build:
    needs: unity_test
    name: Unity Build (Android)
    runs-on: ubuntu-latest
    environment: UnityProject
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetPlatform: Android
          allowDirtyBuild: true

  webgl_build:
    needs: unity_test
    name: Unity Build (WebGL)
    runs-on: ubuntu-latest
    environment: UnityProject
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetPlatform: WebGL
          allowDirtyBuild: true

  ios_build:
    needs: unity_test
    name: Unity Build (iOS)
    runs-on: ubuntu-latest
    environment: UnityProject
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetPlatform: iOS
          allowDirtyBuild: true

  upload_artifact:
    needs: [windows_build, android_build, webgl_build, ios_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: build
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

