
name: Unity CI

on: [push, pull_request]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  unity_test:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    environment: UnityProject
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Test Runner
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  windows_build:
    needs: unity_test
    name: Unity Build (Windows)
    runs-on: ubuntu-latest
    environment: UnityProject
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true
      - name: Upload Build Artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Build
          path: build/StandaloneWindows64/

  android_build:
    needs: unity_test
    name: Unity Build (Android)
    runs-on: ubuntu-latest
    environment: UnityProject
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetPlatform: Android
          allowDirtyBuild: true
      - name: Upload Build Artifact (Android)
        uses: actions/upload-artifact@v3
        with:
          name: Android-Build
          path: build/Android/

  webgl_build:
    needs: unity_test
    name: Unity Build (WebGL)
    runs-on: ubuntu-latest
    environment: UnityProject
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetPlatform: WebGL
          allowDirtyBuild: true
      - name: Upload Build Artifact (WebGL)
        uses: actions/upload-artifact@v3
        with:
          name: WebGL-Build
          path: build/WebGL/

  ios_build:
    needs: unity_test
    name: Unity Build (iOS)
    runs-on: ubuntu-latest
    environment: UnityProject
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetPlatform: iOS
          allowDirtyBuild: true
      - name: Upload Build Artifact (iOS)
        uses: actions/upload-artifact@v3
        with:
          name: iOS-Build
          path: build/iOS/

