name: Unity CI

on: [push, pull_request]

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    environment: UnityProject

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Unity Test Runner
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: UnityProject
          githubToken: ${{ secrets.GITHUB_TOKEN }}

